Made changes recommended on Nav/Footer & Homepage
SamiFdev/Portfoliov2 pull request #9
Opened 2022-06-17 16:07 UTC by SamiFdev

# Nav Changes

* Set up NavLink to show active link with rounded border and scaled. 
* Removed the padding. 
* Added transition delays to the hover effects

# Footer Changes

* Wrapped links and set it up with flex-direction column. 
* Moved Copyright below the icons.
* Icons have a hover effect now where they change color.
* Added slight padding + Gap and Background Color.

# Home Changes

* Added gap and padding to the write ups so they weren't pushing up against the borders.
* Rounded off the borders so the page didn't appear so outdated and boxy.

2022-06-17 21:55 UTC, arfusop requested changes
Much better, one small thing

2022-06-17 21:55 UTC, arfusop commented on src/components/Navbar/Navbar.module.css
> +    height: 6%;
Generally not a good idea to rely on percentages for stuff like this. Use pixels or rem for what you want to achieve. % will scale based on viewport size and will often not be ideal

2022-06-21 22:42 UTC, arfusop requested changes

2022-06-21 22:42 UTC, arfusop commented on src/components/Footer/Footer.module.css
> +    background-color: steelblue;
Perfect time to use a css variable. You're relying on this color as your primary "background" or accent color, so add it to your global css file as a variable with a name that makes most sense, something like `--primary-accent`. Then call it everywhere you use it. That way, if you ever do switch the color, you only have to update one place instead of many

2022-06-21 22:42 UTC, arfusop commented on src/components/Home/Home.module.css
> +    box-shadow: inset 600px 300px 6px 0px steelblue;
Advice, the blurb hover changes the background color to steelblue, you should also change the font color to white for the entire card. Black on blue is not very UX friendly, whereas white and blue are perfect

2022-06-21 22:42 UTC, arfusop commented on src/components/Home/Home.module.css
> +    animation: typing 4.5s steps(50), blink-caret 0.5s step-end infinite;
💪

2022-06-21 22:42 UTC, arfusop commented on src/components/Navbar/Navbar.module.css
>  .nav {
Your nav links lost their transition on hover. They just grow in size now instead of smoothly transitioning to their hovered size

2022-06-21 22:42 UTC, arfusop commented on src/components/Projects/Projects.module.css
> +    transition-delay: 0.25s;
Transition delay only adds a delay to before the transition starts. It's not actually putting a transition. Replace with `transition: 0.25s` and you'll get what you probably were going for, which would be better

2022-06-21 22:42 UTC, arfusop commented on src/components/Skills/Skills.module.css
> +    transition-delay: 0.25s;
Same as above, transition instead of transition delay.

2022-06-22 18:32 UTC, SamiFdev commented on src/components/Footer/Footer.module.css
> +    background-color: steelblue;
good call, did this.

2022-06-22 22:41 UTC, arfusop requested changes

2022-06-22 22:41 UTC, arfusop commented on src/components/Navbar/Navbar.module.css
> +    /* overflow: hidden;
lets remove the commented out code

2022-06-22 22:41 UTC, arfusop commented on src/components/Navbar/Navbar.module.css
> +    transition-delay: 0.35s;
transition-delay -> transition

2022-06-22 22:41 UTC, arfusop commented on src/components/Projects/Projects.module.css
> +    /* -webkit-transform: scale(1.1);
Remove comments

2022-06-22 22:41 UTC, arfusop commented on src/components/Navbar/Navbar.module.css
> +    /* overflow: hidden;
Remove comments

2022-06-22 22:41 UTC, arfusop commented on src/components/Projects/index.js
> +            <h1>Check Out Some Previous Work</h1>
`Check out some of my work` instead of some previous work

2022-06-24 13:22 UTC, arfusop requested changes

2022-06-24 13:22 UTC, arfusop commented on src/components/Home/Home.module.css
> +    /* overflow: hidden;
Remove comments bruh

2022-06-28 17:53 UTC, merged